### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by taznica** [ttsutchi/MicraGO#1]
# TODO
- [ ] Cube
  - [ ] ItemCube
    - [x] spawn entityCube
    - [ ] renderer
  - [ ] EntityCube
    - [x] capture sheep
    - [x] drop fullCube
    - [ ] apply to all MOBs
      - [ ] get entity ID
    - [ ] particle
    - [ ] renderer
- [ ] FullCube
  - [ ] ItemFullCube
    - [x] spawn entityFullCube
    - [ ] renderer
  - [ ] EntityFullCube
    - [x] spawn sheep
    - [ ] apply to all MOBs
    - [ ] come back
    - [ ] particle
    - [ ] renderer
- [ ] Achievements
  - [ ] add
  - [ ] get
- [ ] Stops

---
# Extras

// - [ ] Gyms

// - [ ] MultiPlay
